# Default values for manager-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.choerodon.com.cn/hzero-hdip/hdsp-quality
  pullPolicy: Always

preJob:
  timeout: 300
  preConfig:
    enable: false
    configFile: application.yml
    datasource:
      url: jdbc:mysql://localhost:3306/manager_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: choerodon
      password: 123456
  preInitDB:
    enable: false
    datasource:
      url: jdbc:mysql://localhost:3306/demo_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: choerodon
      password: 123456

env:
  open:
    # 是否自动刷新服务权限
    CHOERODON_EUREKA_EVENT_PARSE_PERMISSION: true
    # Eureka 注册中心地址
    EUREKA_DEFAULT_ZONE: http://hzero-register.hdsp:8000/eureka
    # 服务以IP地址注册
    EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    # 是否启用配置中心
    SPRING_CLOUD_CONFIG_ENABLED: true
    SPRING_PROFILES_ACTIVE: default
    # 配置中心地址
    SPRING_CLOUD_CONFIG_URI: http://hzero-config.hdsp:8610
    # 数据库地址
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql.hdsp-storage:3306/hdsp_quality?useUnicode=true&characterEncoding=utf-8&useSSL=false
    # 数据库用户名
    SPRING_DATASOURCE_USERNAME: hdsp_test
    # 数据库密码
    SPRING_DATASOURCE_PASSWORD: hdsp_test123$%^
    # Redis host
    SPRING_REDIS_HOST: redis.hdsp-storage
    # Redis DB
    SPRING_REDIS_DATABASE: 1
    SPRING_REDIS_PORT: 6379
    # Hystrix 熔断超时时间
    HYSTRIX_COMMAND_TIMEOUT_IN_MILLISECONDS: 40000
    # Ribbon 读取超时时间
    RIBBON_READ_TIMEOUT: 30000
    # Ribbon 连接超时时间
    RIBBON_CONNECT_TIMEOUT: 3000
    # 日志级别
    LOG_LEVEL: info

    # hdsp-quality


    JAVA_OPTS: >
      -Xms500m
      -Xmx500m
      -DLICENSE.MAC.VERIFY=false

metrics:
  path: /prometheus
  group: spring-boot

logs:
 parser: spring-boot

persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  # subPath:

service:
  name: hdsp-quality
  enabled: false
  type: ClusterIP
  port: 8547

deployment:
  managementPort: 8548
  
ingress:
  enabled: false

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 1.5Gi
  requests:
    # cpu: 100m
    memory: 1Gi

hzero:
  HZERO_NODE_GROUP_ID: 0
  HZERO_PRODUCT_CODE: DEFAULT
  HZERO_PRODUCT_VERSION_CODE: DEFAULT
  HZERO_PRODUCT_ENV_CODE: DEFAULT
  HZERO_SERVICE_VERSION_CODE: DEFAULT
